tasks:
  - before: >
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/gitpod/backend/python/gitpod-setup.sh &&
      chmod 0755 database-setup.sh &&
      bash database-setup.sh 3.7.10
    init: |
      pip install --upgrade pip
      python -m pip install Flask==1.1.1
      pip install -r requirements.txt
    command: python restapi.py

ports:
  - port: 8080
    name: "Backend Server"
    onOpen: open-browser
    visibility: public
  - port: 3306
    name: "MySQL Server"
    onOpen: ignore
    visibility: public
  - port: 27017
    name: "MongoDB Server"
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-python.python
